/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Alfy API
 * The Alfy API documentation
 * OpenAPI spec version: 1.0
 */
export interface ShoppingListItemDTO {
  /** The name of the shopping item */
  name: string;
  /** Whether the item has been bought */
  bought: boolean;
  /** The quantity of the item */
  quantity: number;
}

export interface CreateShoppingListDTO {
  /** The name of the shopping list */
  name: string;
  /** The bought status of the shopping list */
  bought: boolean;
  /** The list of items in the shopping list */
  list: ShoppingListItemDTO[];
}

export interface ShoppingListItemEntity {
  /** The unique identifier of the item */
  id: string;
  /** The name of the shopping item */
  name: string;
  /** The quantity of the item */
  quantity: number;
  /** Whether the item has been bought */
  bought: boolean;
}

export interface ShoppingList {
  /** The unique identifier of the shopping list */
  _id: string;
  /** The name of the shopping list */
  name: string;
  /** Whether the shopping list is completed */
  bought: boolean;
  /** The list of items in the shopping list */
  list: ShoppingListItemEntity[];
  /** Creation timestamp */
  createdAt: string;
  /** Last update timestamp */
  updatedAt: string;
}

export interface UpdateShoppingListDto {
  /** The name of the shopping list */
  name?: string;
  /** The bought status of the shopping list */
  bought?: boolean;
  /** The list of items in the shopping list */
  list?: ShoppingListItemDTO[];
}
