/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Alfy API
 * The Alfy API documentation
 * OpenAPI spec version: 1.0
 */
import { HttpClient } from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse,
} from '@angular/common/http';

import { Injectable } from '@angular/core';

import { Observable } from 'rxjs';

import type { BaseResponseDto, BootstrapSysadminDto } from '../alfyAPI.schemas';

type HttpClientOptions = {
  headers?:
    | HttpHeaders
    | {
        [header: string]: string | string[];
      };
  context?: HttpContext;
  observe?: any;
  params?:
    | HttpParams
    | {
        [param: string]:
          | string
          | number
          | boolean
          | ReadonlyArray<string | number | boolean>;
      };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};

@Injectable({ providedIn: 'root' })
export class BootstrapService {
  constructor(private http: HttpClient) {}
  /**
   * Creates the first sysadmin user. Can only be called once - when no sysadmin exists.
   * @summary Bootstrap the first sysadmin user
   */
  bootstrapControllerBootstrapSysadmin<TData = BaseResponseDto>(
    bootstrapSysadminDto: BootstrapSysadminDto,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
  bootstrapControllerBootstrapSysadmin<TData = BaseResponseDto>(
    bootstrapSysadminDto: BootstrapSysadminDto,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  bootstrapControllerBootstrapSysadmin<TData = BaseResponseDto>(
    bootstrapSysadminDto: BootstrapSysadminDto,
    options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;
  bootstrapControllerBootstrapSysadmin<TData = BaseResponseDto>(
    bootstrapSysadminDto: BootstrapSysadminDto,
    options?: HttpClientOptions
  ): Observable<TData> {
    return this.http.post<TData>(
      `/api/bootstrap/sysadmin`,
      bootstrapSysadminDto,
      options
    );
  }
}

export type BootstrapControllerBootstrapSysadminClientResult =
  NonNullable<BaseResponseDto>;
